spring:
  datasource:
    url: jdbc:mysql://localhost:3306/testcase
    username: root
    password: Sepdesktop@9786
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
  application:
    name: dept-service
server:
  port: 8082
 
